version: 2
jobs:
  build:
    docker:
      - image: cypress/base:10
        environment:
          TERM: xterm
    working_directory: ~/w
    steps:
      - checkout
      - run: yarn install
      - run: yarn cypress run
      - store_artifacts:
          path: cypress/videos
      - store_artifacts:
          path: cypress/screenshots

workflows:
  version: 2
  pipeline:
    jobs:
      - build
